site_name: Moichuelo – Registro
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
  palette:
    - scheme: default        # claro
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate          # oscuro
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight


nav:
  - Overview: Overview.md
  - Development Environment: Development-Environment.md
  - Version Control Configuration: Version-Control-Configuration.md

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js